version: '2'
services:
    dynamodb:
        image: amazon/dynamodb-local
        container_name: dynamodb
        ports:
            - "8000:8000"
        volumes:
            - dynamodata:/data
        command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ."
        networks:
            - my-network
    imaging-app:
        depends_on:
            - dynamodb
        container_name: imaging-app
        build: .
        ports:
            - "5000:5000"
        environment:
            - AWS_ACCESS_KEY_ID=fakeid
            - AWS_SECRET_ACCESS_KEY=fakekey
            - NODE_ENV=dev
            - PORT=5000
            - AWS_REGION=localhost
            - AWSDynamoUrl=http://dynamodb:8000
        networks:
            - my-network
volumes:
    dynamodata:

networks:
    my-network:
        driver: bridge
