version: '2'
services:
  dynamodb:
    image: amazon/dynamodb-local
    container_name: dynamodb
    ports:
      - '8000:8000'
    volumes:
      - dynamodata:/data
    command: '-jar DynamoDBLocal.jar -sharedDb -dbPath .'
    networks:
      - my-network
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - '9000:9000'
    volumes:
      - datastore:/data
    environment:
      - 'MINIO_ACCESS_KEY=minio'
      - 'MINIO_SECRET_KEY=minio123'
    command: server /data
    networks:
      - my-network

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 minio minio123;
      /usr/bin/mc mb myminio/annaliseimagebucket;
      /usr/bin/mc policy set public myminio/annaliseimagebucket;
      exit 0;
      "
  imaging-app:
    depends_on:
      - dynamodb
      - minio
    container_name: imaging-app
    build: .
    ports:
      - '5000:5000'
    environment:
      - AWS_ACCESS_KEY_ID=fakeid
      - AWS_SECRET_ACCESS_KEY=fakekey
      - NODE_ENV=dev
      - PORT=5000
      - AWS_REGION=localhost
      - AWSDynamoUrl=http://dynamodb:8000
    networks:
      - my-network
volumes:
  dynamodata:
  datastore:

networks:
  my-network:
    driver: bridge
