swagger: '2.0'
info:
  description: API Documentation
  version: 1.0.0
  title: Image labeling API
  contact:
    email: admin@akhilbiswas.com
  license:
    name: 'Private'
    url: 'http://akhilbiswas.com'

basePath: /api/v1/
tags:
  - name: Image Labeling System
    description: This APIs saved the images and search them
schemes:
  - http
securityDefinitions:
  APIKeyHeader:
    type: apiKey
    in: header
    name: X-API-KEY
security:
  - APIKeyHeader: []

paths:
  /imagelabels:
    get:
      tags:
        - Image label
      operationId: getMetadataHandler
      summary: Search
      description: Search
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: diseaseType
          in: query
          required: true
          type: string
          description: diseaseType
      responses:
        200:
          description: found results
    post:
      tags:
        - Image label
      operationId: createPostHandler
      summary: Uploads a image file
      consumes:
        - multipart/form-data
      parameters:
        - in: formData
          name: file
          type: file
          description: The image file to upload.
        - name: diseasetype
          in: query
          required: true
          type: string
          description: disease type
      responses:
        201:
          description: successfully added the image and metadata
